sources:
  - name: "local-postgres"
    kind: postgres
    postgres:
      host: "localhost"
      port: 5432
      user: postgres
      password: postgres

queue:
  name: test-queue
  kind: kafka
  kafka:
    bootstrap_servers: localhost:9092
