sources:
  - name: "local-postgres"
    source_type: postgres
    host: "localhost"
    port: 5432
    user: postgres
    password: postgres

queue:
  kind: kafka
  name: test-queue
  kafka_config:
    bootstrap_servers: localhost:9092
