sources:
  - name: "local-postgres"
    kind: postgres
    postgres_config:
      host: "localhost"
      port: 5432
      user: postgres
      password: postgres

queue:
  kind: kafka
  name: test-queue
  kafka_config:
    bootstrap_servers: localhost:9092
