[package]
name = "dms-examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dms-examples"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.69"
tokio = { version = "1.25.0", features = ["full"] }
dms = { path = "../dms" }
